---
!bind
$Values:
  count: 3

---
!bind
$Idx: !range
  $from: 0
  $until: !ref $Values.count
  $as: $I
  $yield: !ref $I
$Seq: !range
  $from: 1
  $to: !ref $Values.count
  $as: $I
  $yield: !ref $I
$Ports: !range
  $from: 3
  $until: 10
  $step: 2
  $as: $I
  $yield: !ref $I

---
!emit
apiVersion: v1
kind: ConfigMap
metadata:
  name: api
data:
  idx: !ref $Idx
  seq: !ref $Seq
  ports: !ref $Ports
