---
!bind
$Values:
  name: api
  extraArgs:
    - --foo
    - --bar

---
!emit
apiVersion: apps/v1
kind: Deployment
metadata:
  name: !ref $Values.name
spec:
  template:
    spec:
      containers:
        - name: app
          args: !foreach
            $over: !ref $Values.extraArgs
            $as: $A
            $yield: !ref $A
